name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Django tests
        env:
          SECRET_KEY: "test-secret-key"
          DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
        run: |
          poetry run python manage.py test order.tests
          poetry run python manage.py test product.tests